language: python
python:
 - "2.7"
 - "3.3"

before_install:
# Workaround for a permissions issue with Travis virtual machine images
# that breaks Python's multiprocessing:
# https://github.com/travis-ci/travis-cookbooks/issues/155
 - sudo rm -rf /dev/shm
 - sudo ln -s /run/shm /dev/shm
 - pip install nose>=1.3.0
 - pip install coverage>=3.6

before_script:
 - for d in python; do pushd $d; ./install; popd; done

script:
 - for d in python; do pushd $d; ./run_tests; popd; done
